from pathlib import Path
import sys

import numpy as np
import matplotlib.pyplot as plt
from netCDF4 import Dataset


# ============================================================
# Project root
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))

from config.l1bConfig import l1bConfig
from common.src.auxFunc import getIndexBand


# ============================================================
# Directories
# ============================================================

TEST_ROOT = Path.home() / "EODP_TER_2021" / "EODP-TS-L1B"

INPUT_DIR = TEST_ROOT / "input"

# Reference outputs provided by the professor
REF_OUTPUT_DIR = TEST_ROOT / "output"

# Outputs generated by my implementation
MY_OUTPUT_DIR = TEST_ROOT / "myoutputs"

# Figures generated by this test
FIGURES_DIR = Path(__file__).resolve().parent / "figures"
FIGURES_DIR.mkdir(exist_ok=True)

# Cross-validation report
VALIDATION_REPORT = Path(__file__).resolve().parent / "cross_validation_L1B.txt"


# ============================================================
# Utilities
# ============================================================

def read_toa(filepath):
    """
    Read the 'toa' variable from a NetCDF file.
    """
    with Dataset(filepath, "r") as dataset:
        return np.array(dataset.variables["toa"][:], dtype=float)


# ============================================================
# Plot: effect of equalization
# ============================================================

def plot_equalization():

    band = "VNIR-0"

    # Central ALT line
    alt_line = 50

    # Radiance after ISRF
    toa_isrf = read_toa(
        INPUT_DIR / f"ism_toa_isrf_{band}.nc"
    )

    # L1B input in DN
    toa_dn = read_toa(
        INPUT_DIR / f"ism_toa_{band}.nc"
    )

    # My final L1B result:
    # equalization + restoration
    toa_l1b_with_eq = read_toa(
        MY_OUTPUT_DIR / f"l1b_toa_{band}.nc"
    )

    # --------------------------------------------------------
    # L1B without equalization
    # --------------------------------------------------------

    config = l1bConfig()

    gain = config.gain[getIndexBand(band)]

    # Only restoration:
    # TOA_L1B = TOA_DN * Gain
    toa_l1b_no_eq = toa_dn * gain

    # ACT axis
    act = np.arange(toa_l1b_with_eq.shape[1])

    # --------------------------------------------------------
    # Plot
    # --------------------------------------------------------

    plt.figure(figsize=(10, 6))

    plt.plot(
        act,
        toa_l1b_with_eq[alt_line, :],
        label="TOA L1B with eq"
    )

    plt.plot(
        act,
        toa_l1b_no_eq[alt_line, :],
        label="TOA L1B no eq"
    )

    plt.plot(
        act,
        toa_isrf[alt_line, :],
        label="TOA after the ISRF"
    )

    plt.title(f"Effect of the Equalization for {band}")

    plt.xlabel("ACT pixel [-]")
    plt.ylabel("TOA [mW/m2/sr]")

    plt.grid(True)
    plt.legend()
    plt.tight_layout()

    figure_path = FIGURES_DIR / f"equalization_{band}.png"

    plt.savefig(
        figure_path,
        dpi=200,
        bbox_inches="tight"
    )

    print(f"Figure saved: {figure_path}")

    plt.show()


# ============================================================
# Cross-validation
# ============================================================

def cross_validation():

    # Maximum allowed relative difference [%]
    limit = 1e-3

    lines = []

    header = (
        f"{'FILE':35s} "
        f"{'MAX ABS':>14s} "
        f"{'MAX REL %':>14s} "
        f"{'RESULT':>8s}"
    )

    separator = "-" * 76

    lines.append(header)
    lines.append(separator)

    overall = True

    # Compare every NetCDF generated by our L1B
    for my_file in sorted(MY_OUTPUT_DIR.glob("*.nc")):

        ref_file = REF_OUTPUT_DIR / my_file.name

        if not ref_file.exists():

            lines.append(
                f"{my_file.name:35s} "
                f"{'-':>14s} "
                f"{'-':>14s} "
                f"{'NO REF':>8s}"
            )

            overall = False
            continue

        # Read TOA arrays
        ref_toa = read_toa(ref_file)
        my_toa = read_toa(my_file)

        # Absolute difference
        diff = np.abs(my_toa - ref_toa)

        max_abs = np.max(diff)

        # Relative difference only where
        # the reference value is not zero
        mask = np.abs(ref_toa) > 1e-15

        if np.any(mask):

            relative_difference = (
                diff[mask]
                / np.abs(ref_toa[mask])
                * 100.0
            )

            max_rel = np.max(relative_difference)

        else:
            max_rel = 0.0

        passed = max_rel < limit

        overall &= passed

        lines.append(
            f"{my_file.name:35s} "
            f"{max_abs:14.6e} "
            f"{max_rel:14.6e} "
            f"{'PASS' if passed else 'FAIL':>8s}"
        )

    lines.append(separator)

    lines.append(
        f"OVERALL: {'PASS' if overall else 'FAIL'}"
    )

    lines.append(
        f"Required limit: {limit} %"
    )

    # Print report in terminal
    report = "\n".join(lines)

    print()
    print("L1B CROSS-VALIDATION")
    print()
    print(report)

    # Save report to file
    VALIDATION_REPORT.write_text(report)

    print()
    print(
        f"Validation report saved: "
        f"{VALIDATION_REPORT}"
    )

    return overall


# ============================================================
# Main test
# ============================================================

if __name__ == "__main__":

    print()
    print("================================")
    print("EODP L1B TEST")
    print("================================")
    print()

    # Generate equalization figure
    plot_equalization()

    # Cross-validation against reference outputs
    result = cross_validation()

    if result:
        print()
        print("L1B TEST RESULT: PASS")
    else:
        print()
        print("L1B TEST RESULT: FAIL")